version: '3'

services:sp
  # Use self-signed SSL certificates for testing
  # For production, please refer to docs/ssl-database.md
  postgresql:
    build:
      context: '.'
      dockerfile: Dockerfile.postgresqlSSL
    ports:
      - '6543:5432'
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - timescaledb-v1.7.1-pg12-data:/var/lib/postgresql/data/pgdata

  elasticsearch:
    build:
      context: '.'
      dockerfile: Dockerfile.elasticsearch
    ports:
      - '9200:9200'
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1

      # Enable authentication
      # If `xpack.security.enabled` is omitted or false, Elasticsearch won't verify the sent credentials
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#general-security-settings
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
    volumes:
      - es-v7.3.2-data:/usr/share/elasticsearch/data

  redis:
    image: redis:5.0.1-alpine
    ports:
      - '36379:6379'
    volumes:
      - redis-v5.0.1-data:/data

volumes:
  timescaledb-v1.7.1-pg12-data:
  es-v7.3.2-data:
  redis-v5.0.1-data:
