initScope: saltana

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-push.cjs
    spec: 'https://yarnplugins.com/push'
  - path: .yarn/plugins/@yarnpkg/plugin-bundle.cjs
    spec: 'https://yarnplugins.com/bundle'

pnpIgnorePatterns:
  - ./playground/**
  - ./docs/*

pnpMode: loose

packageExtensions:
  "elastic-apm-node@*":
    dependencies:
      parseurl: "*"
  cote@*:
    dependencies:
      debug: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  "@reach/alert@*":
    dependencies:
      prop-types: "*"
  "@chakra-ui/accordion@*":
    dependencies:
      framer-motion: "*"
      react-dom: "*"
  next-auth@*:
    peerDependenciesMeta:
      "@prisma/client":
        optional: true

yarnPath: .yarn/releases/yarn-sources.cjs
