version: '3'

services:
  elasticsearch:
    build:
      context: '.'
    ports:
      - '9200:9200'
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1

      # Enable authentication
      # If `xpack.security.enabled` is omitted or false, Elasticsearch won't verify the sent credentials
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#general-security-settings
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD="${ELASTIC_SEARCH_PASSWORD:-elastic_password}"
    volumes:
      - es-v7.3.2-data:/usr/share/elasticsearch/data

volumes:
  es-v7.3.2-data:
